version: '3'
services:
  api:
    build:
      context: ./node
    image: guidoin/testchat-app
    ports:
      - 8080
    links:
      - dbmem:redis
    container_name: testchat-app
    environment:
      - LOG_NODE_EVENT_SOCKET=PROD
    networks:
      - internal
    # resources:
    #   limits:
    #     cpus: '0.1'
    #   reservation:
    #     cpus: '0.001'
  static:
    image: nginx:alpine
    volumes:
      - ./site/build:/usr/share/nginx/html
    container_name: static-files
    ports:
      - 80
    environment:
      - NGINX_PORT=80
    networks:
      - internal
  dbmem:
    image: redis:alpine
    container_name: redis
    networks:
      - internal
  chatbot:
    build:
      context: ./ChatBot
    image: guidoin/chatbot
    container_name: chatbot
    links:
      - reverse:reverse
    networks:
      - external
    ports:
      - 80
  reverse:
    image: haproxy:alpine
    volumes:
      - ./reverse-proxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    container_name: reverse
    ports:
      - 80:80
    links:
      - api
      - static
    networks:
      - internal
      - external
networks:
  internal:
  external:
