version: '2'
services:
  api:
    build:
      context: ./node
    image: guidoin/testchat-app
    ports:
      - 8080
    links:
      - dbmem:redis
    environment:
      - LOG_NODE_EVENT_SOCKET=DEV
    networks:
      internal:
        aliases:
          - api
  static:
    build:
      context: ./site
    image: guidoin/nginx-testchatapp
    # volumes:
    #   - ./site/build:/usr/share/nginx/html
    container_name: static-files
    ports:
      - 80
    environment:
      - NGINX_PORT=80
    networks:
      internal:
        aliases:
          - static
  dbmem:
    image: redis:alpine
    container_name: redis
    networks:
      internal:
        aliases:
          - dbmem
  reverse:
    build:
      context: ./reverse-proxy
    image: guidoin/haproxy-testchat
    container_name: reverse
    ports:
      - 80:80
    depends_on:
      - static
      - api
    networks:
      - internal
      - external
  # chatbot:
  #   build:
  #     context: ./ChatBot
  #   image: guidoin/chatbot
  #   container_name: chatbot
  #   depends_on:
  #     - reverse
  #   networks:
  #     - external
  #   ports:
  #     - 80
networks:
  internal:
  external:
